server:
  port: 8082
spring:
  application:
    name: teacher-service-router
eureka:
  client:
    service-url:
      defaultZone: http://192.168.168.168:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true

