server:
  port: 81 #网关一般是80
spring:
  application:
    name: gateway-server-1
  cloud:
    gateway:
      enabled: true #开启网关，默认是开启的，只要加了依赖 默认开启
      routes: #设置路由，注意是数组，可以设置多个，按照 id 做隔离，如果一个服务里面有100个路径  如果我想做负载均衡 ??   动态路由
        - id: user-service-router #这个是路由 id，没有要求，保持唯一即可
          uri: http://192.168.226.1:8081 #设置真正的服务 ip:port    uri统一资源定位符   url 统一资源标识符
          predicates: #断言匹配 断言是给某一个路由来设定的一种匹配规则 默认不能作用在动态路由上
            - Path=/info/** #和服务中的路径匹配,是正则匹配的模式
        - id: provider-service-router
          uri: http://192.168.226.1:8082
          predicates:
            - Path=/info/** #如果匹配到第一个路由，则第二个就不会走了，注意这不是负载均衡
#eureka 的配置
eureka:
  client:
    service-url:
      defaultZone: http://192.168.168.168:8761/eureka
    registry-fetch-interval-seconds: 3 # 网关拉取服务列表的时间缩短
    register-with-eureka: true #是否注册自己（单机 eureka 一般关闭注册自己,集群注意打开）
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true

