server:
  port: 80 #网关一般是80
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由  开启通过应用名称 找到服务的功能
          lower-case-service-id: true  # 开启服务名称小写
      enabled: true #开启网关，默认是开启的，只要加了依赖 默认开启
      routes:
        - id: user-service-router
          uri: lb://user-service
          predicates:
            - Path=/doLogin #请求路径必须符合指定规则
            - After=2022-03-22T08:42:59.521+08:00[Asia/Shanghai] #是某个时间点后的请求
            - Method=GET,POST #请求方式必须是指定方式
            - Query=name,admin. #请求参数必须包含指定参数 正则表达式
#          filters:
#            - name: RequestRateLimiter  # 这个是过滤器的名称
#              args: # 这个过滤器的参数
#                key-resolver: '#{@apiKeyResolver}' # 通过spel表达式取 ioc容器中bean的值
#                redis-rate-limiter.replenishRate: 1  # 生成令牌的速度
#                redis-rate-limiter.burstCapacity: 1  # 桶容量
#eureka 的配置
eureka:
  client:
    service-url:
      defaultZone: http://192.168.168.168:8761/eureka
    registry-fetch-interval-seconds: 3 # 网关拉取服务列表的时间缩短
    register-with-eureka: true #是否注册自己（单机 eureka 一般关闭注册自己,集群注意打开）
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true

